apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-substreams-tier2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: substreams-tier2
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
