apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: substreams-tier2
  labels:
    app: substreams-tier2
spec:
  jobLabel: substreams-tier2
  selector:
    matchLabels:
      app: substreams-tier2
  endpoints:
  - port: prom
    path: /metrics