apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: substreams-tier2-vpa
  namespace: sf-ethereum
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       substreams-tier2
  updatePolicy:
    updateMode: "Auto"