apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: relayer-config
data:
  config.yaml: |
    start:
      args:
      - relayer
      flags:
        verbose: "1"
        common-chain-id: "1"
        common-network-id: "1"
        log-to-file: false
        data-dir: "/var/lib/fireeth"
        common-one-block-store-url: "s3://seaweedfs:8333/fireeth-one-blocks?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        common-merged-blocks-store-url: "s3://seaweedfs:8333/fireeth-merged-blocks?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        common-forked-blocks-store-url: "s3://seaweedfs:8333/fireeth-forked-blocks?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        common-index-store-url: "s3://seaweedfs:8333/fireeth-index?region=none&insecure=true&access_key_id=any_no_empty_key&secret_access_key=any_no_empty_key"
        relayer-source: "reader-node:13010"
