---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 6h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
  annotations:
    helm.fluxcd.io/uninstall: true
spec:
  interval: 6h
  chart:
    spec:
      chart: loki-stack
      version: "2.9.11"
      sourceRef:
        kind: HelmRepository
        name: loki
  targetNamespace: monitoring
  install:
    createNamespace: true
  values:
    loki:
      enabled: true
      isDefault: false
      datasource:
        jsonData: 
          derivedFields:
          - name: "traceID"
            matcherRegex: "trace_id=(\\w+)"
            url: "$${__value.raw}"
            datasourceUid: Tempo
        uid: loki
    promtail:
      enabled: true
      config:
        scrape_configs:
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_node_name]
                target_label: __host__
              - source_labels: [__meta_kubernetes_pod_label_app]
                target_label: app
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              - source_labels: [__meta_kubernetes_pod_container_name]
                target_label: container
              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - action: replace
                replacement: /var/log/pods/*$1/*.log
                regex: (.+)
                source_labels: [__meta_kubernetes_pod_uid]
                target_label: __path__