---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: odigos
  namespace: flux-system
spec:
  interval: 6h
  url: https://keyval-dev.github.io/odigos-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: odigos
  namespace: flux-system
  annotations:
    helm.fluxcd.io/uninstall: true
spec:
  interval: 6h
  chart:
    spec:
      chart: odigos
      version: "0.2.39"
      sourceRef:
        kind: HelmRepository
        name: odigos
  targetNamespace: monitoring
  install:
    createNamespace: true