---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 6h
  url: https://openebs.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: flux-system
  annotations:
    helm.fluxcd.io/uninstall: true
spec:
  interval: 6h
  chart:
    spec:
      chart: openebs
      version: "3.10.0"
      sourceRef:
        kind: HelmRepository
        name: openebs
  targetNamespace: openebs
  install:
    createNamespace: true
  values:
    localprovisioner:
      basePath: "/tank-ssd"
