---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 6h
  url: https://stakater.github.io/stakater-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: flux-system
  annotations:
    helm.fluxcd.io/uninstall: true
spec:
  interval: 6h
  chart:
    spec:
      chart: reloader
      version: "1.0.51"
      sourceRef:
        kind: HelmRepository
        name: reloader
  targetNamespace: reloader
  install:
    createNamespace: true