---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tempo
  namespace: flux-system
spec:
  interval: 6h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
  annotations:
    helm.fluxcd.io/uninstall: true
spec:
  interval: 6h
  chart:
    spec:
      chart: tempo
      version: "1.6.3"
      sourceRef:
        kind: HelmRepository
        name: tempo
  targetNamespace: monitoring
  install:
    createNamespace: true
  values: 
    tempo:
      extraArgs:
        distributor.log-received-traces: true
    config: |
      service_graphs:
        enabled: true