apiVersion: v1
kind: ConfigMap
metadata:
  name: sf-metering-sink-config
data:
  config.yaml: |
    application:
      gin_mode: "debug"
      http_host: "0.0.0.0:8080"
      grpc_host: "0.0.0.0:9000"
      domain: ""
    
    sinks_enabled:
      #- name: redis
      #  event_aggregation: true
      #- name: elastic
      #  event_aggregation: true
      #- name: clickhouse
      #  event_aggregation: true
      - name: log
        event_aggregation: true