apiVersion: v1
kind: ConfigMap
metadata:
  name: sf-metering-sink-config
data:
  config.yaml: |
    application:
      gin_mode: "debug"
      http_host: "0.0.0.0:8080"
      grpc_host: "0.0.0.0:9000"
      domain: ""
    
    sinks_enabled:
      #- name: redis
      #  event_aggregation: true
      #- name: elastic
      #  event_aggregation: true
      #- name: clickhouse
      #  event_aggregation: true
      - name: log
        event_aggregation: true
    
    clickhouse:
      hosts:
        - "localhost:9000"
      user: "default"
      password: "secret"
      database: "usage_v1"
      max_open_conns: 10
      max_idle_conns: 10
    
    elastic:
      index: "dev-sf-usage-v1"
      num_workers: 4
      user: "sf-dev"
      password: "secret"
      hosts:
        - "http://esh1-master1.mar.eosn.io:9200"
        - "http://esh1-master2.mar.eosn.io:9200"
        - "http://esh1-master3.mar.eosn.io:9200"
    
    redis:
      hosts:
        - 127.0.0.1:26379
      master_name: "mymaster"
      trace_key_ttl: 10s