apiVersion: v1
kind: Service
metadata:
  name: firehose-svc
spec:
  type: ClusterIP
  selector:
    app: firehose
  ports:
    - name: grpc
      port: 13042
      protocol: TCP
      targetPort: grpc
