apiVersion: v1
kind: ConfigMap
metadata:
  name: pinax-authenticator-config
data:
  config.yaml: |
    application:
      gin_mode: "debug"
      http_host: "0.0.0.0:8080"
      grpc_host: "0.0.0.0:9000"
      domain: "http://localhost:8080"
    
    mysql:
      is_galera_cluster: true
      balancing_mode: "ordered"
      user: "pinax_authenticator_staging"
      password: "secret_staging"
      database: "pinax_cloud_staging"
      connections:
        - host: "mar-db11.mar.eosn.io"
          port: 3306
        - host: "mar-db12.mar.eosn.io"
          port: 3306
        - host: "mar-db13.mar.eosn.io"
          port: 3306
    
    api_key:
      hmac_secret: "secrethmacsecret"
    
    # configs to set up the signing of JWTs
    jwt_signing:
      audience: "https://account.pinax.network/"
      signing_key: "zN2RLkhkjcmqTro7TdoaUQuF"
      signing_algorithm: "HS256"
      issuer: "https://api.dev.pinax.network/v1/"    
    
    sf_jwt_validation:
      signing_algorithm: "KMSES256"
      jwks_url: "https://storage.googleapis.com/dfuseio.com/.well-known/jwks.json"
      issuer: "dfuse.io"
    
    #ip_allow_list:
    #  file: "."
    
    redis:
      hosts:
        - "172.22.3.164:26379"
        - "172.22.3.165:26379"
        - "172.22.3.166:26379"
      master_name: "mymaster"