---    
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pinax-cloud-backend
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - network_policy.yaml
