---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-volume-zookeeper-0
spec:
  resources:
    requests:
      storage: 25Gi
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
