# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: grafana-stripprefix
# spec:
#   stripPrefix:
#     prefixes:
#       - /tier1
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: sf-ethereum
  name: substreams-tier1
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/tier1`)
      kind: Rule
      services:
        - name: substreams-tier1
          port: 9000
      # middleware:
      #   - name: grafana-stripprefix