---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: substreams-tier1
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/a`)
      kind: Rule
      services:
        - name: substreams-tier1
          port: 9000