apiVersion: v1
kind: ConfigMap
metadata:
  name: pinax-account-api-config
data:
  config.yaml: |
    application:
      gin_mode: "debug"
      http_host: "0.0.0.0:8080"
      grpc_host: ""
      domain: "http://localhost:8080"
    
    auth0:
      auth0_domain: "pinax-dev.us.auth0.com"
      namespace: "https://dev.pinax.network/"
      auth0_allowed_audiences:
        - "https://api.dev.pinax.network/v1/"
      management_domain: "pinax-dev.us.auth0.com"
      client: "oYTbWmnOXZMCzsqXkZnjUu3JzneS2oO2"
      secret: "LRl94s-hLNij2BaFgxEIU499i1UsCCY4vwU9lG1MoVotZnNFxmdmgDndgwfJ4d0U"

    database:
      is_galera_cluster: true
      balancing_mode: "ordered"
      user: "pinax_api_staging"
      password: "secret_staging"
      database: "pinax_cloud_staging"
      connections:
        - host: "mar-db11.mar.eosn.io"
          port: 3306
        - host: "mar-db12.mar.eosn.io"
          port: 3306
        - host: "mar-db13.mar.eosn.io"
          port: 3306
    
    api_key:
      hmac_secret: "secrethmacsecret"
    
    # configs to set up the signing of JWTs
    elasticsearch:
      user: "sf-dev"
      password: "zAvku0-pibfyn-vapnem"
      hosts:
        - "http://esh1-master1.mar.eosn.io:9200"
        - "http://esh1-master2.mar.eosn.io:9200"
        - "http://esh1-master3.mar.eosn.io:9200"
      index: "dev-sf-history-v1"   
    
    sf_jwt_validation:
      signing_algorithm: "KMSES256"
      jwks_url: "https://storage.googleapis.com/dfuseio.com/.well-known/jwks.json"
      issuer: "dfuse.io"
    
    migration:
      migration_dir: "/app/migrations"
    
    audit:
      file_dir: ""
      to_database: true
      to_console: false