operator:
  prometheus:
    enabled: true
    serviceMonitor: 
      enabled: true

hubble:
  enabled: true
  listenAddress: ":4244"
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    serviceMonitor: 
      enabled: true
  relay:
    enabled: true
    prometheus: 
      enabled: true
      serviceMonitor: 
        enabled: true
  ui:
    enabled: true

envoy:
  enabled: true
  prometheus: 
    enabled: true
    serviceMonitor: 
      enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    spec:
      endpoints:
        - port: envoy-metrics

rollOutCiliumPods: true

# loadBalancer:
#   l7:
#     algorithm: least_request
#     backend: enabled